select * from customer where 1;
select * from car where type="compact";
select * from car where type="medium";
select * from car where type="large";
select * from car where type="suv";
select * from car where type="truck";
select * from car where type="van";
select * from car_type where 1;
select * from rentals where 1;